services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_api
    environment:
      NODE_ENV: development
      PORT: "3000"
      CORS_ORIGIN: http://localhost:5173
      DATABASE_URL: postgres://banco:banco@db:5432/banco
    depends_on:
      db:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_web
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://api:3000
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./frontend:/app        # monta el código en /app
      - /app/node_modules      # volumen anónimo: no pises node_modules
    depends_on:
      api:
        condition: service_started
  db:
    image: postgres:16
    container_name: app_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: banco
      POSTGRES_PASSWORD: banco
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
