version: "3.9"
services:
  db:
    image: postgres:16
    container_name: app_db
    environment:
      POSTGRES_USER: banco
      POSTGRES_PASSWORD: banco
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_api
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://banco:banco@db:5432/banco
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_web
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
